apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: us-west-2

managedNodeGroups:
  - name: prod
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 6
    spot: true
    ssh:
      allow: true
    iam:
      withAddonPolicies:
        cloudWatch: true
