apiVersion: eksctl.io/v1alpha5
kind: ClusterConfig
metadata:
  name: eks-demo
  region: us-west-2

iam:
  withOIDC: true
  serviceAccounts:
    - metadata:
        name: aws-load-balancer-controller
        namespace: kube-system
      wellKnownPolicies:
        awsLoadBalancerController: true

managedNodeGroups:
  - name: prod
    instanceType: t3.medium
    desiredCapacity: 1
    minSize: 1
    maxSize: 6
    spot: true
    iam:
      withAddonPolicies:
        cloudWatch: true

gitops:
  flux:
    gitProvider: github
    flags:
      owner: "enschede"
      repository: "eks-demo-infra"
      private: "true"
      branch: "main"
      namespace: "flux-system"
      path: "app-cluster"
